### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by ghost** [MikeBild/excel-couchdb-import#2]
Hello, I have excel file I'd like to push to PouchDB and that's how I found the repo. Was there a way to send command with Windows10?

**Comment by MikeBild** [comment]
Install globally via npm.

`npm i -g excel-couchdb-import`

After installation try: 

`excel-couchdb-import ./myexcel.xlsx --target http://username:password@your-pouchdb.domain.com/database`

This should do what you need.
