### ISSUE TITLE
Mango query reserved $type as operator

### ISSUE THREAD

**Issue by sim2github** [MikeBild/excel-couchdb-import#7]
Can't use `Mango query`  in `Fauxton`:
```javascript
{
   "selector": {
      "$type": {
         "$eq": "Genre"
      }
   }
}
```

**Error running query. Reason: (bad_arg) Bad argument for operator $type**

`$type` conflict with [condition-operators](http://docs.couchdb.org/en/2.0.0/api/database/find.html#condition-operators) in find documents querying syntax.

I fix this by changing `$type` by `doc_type` in followed lines:

https://github.com/MikeBild/excel-couchdb-import/blob/ce34209436146b1f7e0a1c3c919c9c7d3a39d935/bin/excel-couchdb-import#L32

https://github.com/MikeBild/excel-couchdb-import/blob/ce34209436146b1f7e0a1c3c919c9c7d3a39d935/lib/parse.js#L29

**Comment by MikeBild** [comment]
Thx! Changed with v4.0.0 on NPM!
